const authGate=document.getElementById('authGate');const siteContent=document.getElementById('siteContent');const signupForm=document.getElementById('signupForm');const loginForm=document.getElementById('loginForm');const authMessage=document.getElementById('authMessage');const tabs=document.querySelectorAll('.auth-tab');
function unlockSite(name=''){localStorage.setItem('toteShirtLoggedIn','true');if(name)localStorage.setItem('toteShirtName',name);authGate.classList.add('hidden');siteContent.classList.add('unlocked');siteContent.setAttribute('aria-hidden','false');document.body.classList.remove('locked');window.scrollTo(0,0);setTimeout(initReveal,80)}
// Keep the sign-up / log-in screen as the first thing visitors see on every open.
localStorage.removeItem('toteShirtLoggedIn');localStorage.removeItem('toteShirtName');authGate.classList.remove('hidden');siteContent.classList.remove('unlocked');siteContent.setAttribute('aria-hidden','true');document.body.classList.add('locked');
tabs.forEach(tab=>tab.addEventListener('click',()=>{const login=tab.dataset.auth==='login';tabs.forEach(t=>t.classList.toggle('active',t===tab));signupForm.classList.toggle('hidden',login);loginForm.classList.toggle('hidden',!login);authMessage.textContent=''}));
signupForm.addEventListener('submit',e=>{e.preventDefault();unlockSite(document.getElementById('firstName').value.trim())});loginForm.addEventListener('submit',e=>{e.preventDefault();unlockSite()});
document.getElementById('logoutBtn').addEventListener('click',()=>{localStorage.removeItem('toteShirtLoggedIn');localStorage.removeItem('toteShirtName');location.reload()});
const menu=document.querySelector('.menu');const links=document.querySelector('.links');menu?.addEventListener('click',()=>{links.classList.toggle('open');menu.setAttribute('aria-expanded',links.classList.contains('open'))});document.querySelectorAll('.links a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
const quantity=document.getElementById('quantity');const total=document.getElementById('total');const payBtn=document.getElementById('payBtn');const paymentMessage=document.getElementById('paymentMessage');function updateTotal(){const qty=Math.min(10,Math.max(1,Number(quantity.value)||1));quantity.value=qty;total.textContent=`₹${(150*qty).toLocaleString('en-IN')}`}quantity?.addEventListener('input',updateTotal);updateTotal();payBtn?.addEventListener('click',()=>{const method=document.querySelector('input[name="payment"]:checked')?.value;const amount=total.textContent;if(method==='cod')paymentMessage.textContent=`Order request ready for ${amount}. We will contact you at toteshirtindia@gmail.com.`;else paymentMessage.textContent=`Checkout is ready for ${amount}. A real payment gateway still needs to be connected before live payments can be accepted.`});
function initReveal(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver' in window)){items.forEach(x=>x.classList.add('visible'));return}const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.12});items.forEach(item=>observer.observe(item))}
if(!document.body.classList.contains('locked'))initReveal();
